### ISSUE TITLE
Slow performance of Perl 6 notebook

### ISSUE THREAD

**Issue by sumandoc** [bduggan/p6-jupyter-kernel#16] opened 2017-09-12 11:52 UTC
Hi there,

Perl 6 notebook is running great. Works fabulous. 
I frequently use R notebook of which [R kernel is here](https://github.com/IRkernel/IRkernel). But compared to the Python and R kernel, Perl 6 notebook runs much slower.

Is it due to the problem in rakudo itself or the Perl 6 kernel ? Or is it due to communication in the sockets?

Best,
Suman

**Comment by bduggan** [comment] 2017-09-12 13:57
Hi Suman,

Could you be a bit more specific about what runs slower?  Have you seen performance differences between Perl 6 code in a notebook and in a standalone program?  (or in the built-in REPL?)

thanks
Brian

**Comment by sumandoc** [comment] 2017-09-12 15:09
Hi Brian,

I mean execution of the Perl 6 code in notebook cell.
Executing `1/3` in REPL is faster than in notebook.

This is the [docker image I used](https://hub.docker.com/r/sumdoc/perl-6-notebook/).


Best,
Suman

**Comment by bduggan** [comment] 2017-09-15 12:49
Hi Suman,

I can confirm the behavior you're seeing -- on my machine even a simple round trip seems to take about 0.7 seconds.  The bad news is I don't see a simple explanation, but the good news is that optimization is definitely possible.

For instance, the HMAC+SHA256 is computed for every message (as part of the protocol) -- this computation takes between 0.10 and 0.15 seconds, and there are several messages involved in generating a response (sending a `status` of `busy` to iopub, then sending an `execute_input` message to iopub, then sending an `execute_result` to iopub, and finally and sending an `execute_reply` to shell), so this computation be a good candidate for optimization.

Brian

**Comment by bduggan** [comment] 2017-09-15 17:58
I think the above commit resolves the slowness -- the response time seems to be a lot better now (closer to 0.1s).   I'll go ahead and close this ticket (not that future optimizations wouldn't help even more of course)

**Closed by bduggan** 2017-09-15 17:58 UTC
